{% set name = "owa-env-gst" %}
{% set version = "0.4.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/owa_env_gst-{{ version }}.tar.gz
  sha256: 9232feacd17534c168919b010a4d34890a8688db543b941c2040678eab4be873

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - owa-core
    - pillow >=11.1.0
    - av >=14.3.0
    - pygobject-stubs >=2.12.0
    - tqdm >=4.67.1
    - opencv >=4.11.0
    - pygobject
    - gst-python ==1.24.11
    - gst-libav ==1.24.11
    - gstreamer ==1.24.11
    - gst-plugins-base ==1.24.11
    - gst-plugins-good ==1.24.11
    - gst-plugins-bad ==1.24.11
    - gst-plugins-ugly ==1.24.11
    - __linux  # [linux]
    - __osx    # [osx]
    - __win    # [win]

test:
  imports:
    - owa.env.gst
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/open-world-agents/open-world-agents
  summary: "Everything you need to build state-of-the-art foundation multimodal desktop agent, end-to-end."
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MilkClouds
